### ISSUE TITLE
train

### ISSUE THREAD

**Issue by lbh1974988541** [placeforyiming/CVPR21-Deep-Lucas-Kanade-Homography#7]
how can i train the model with my dataset
run train_level_one two three .train_regression_first second third?

**Comment by placeforyiming** [comment]
> how can i train the model with my dataset run train_level_one two three .train_regression_first second third?

It's depending on your applications. The current method aims to align two images in sub-pixel accuracy with a relatively good initial. So if you already have a good guess about the image transformation, it should be ok to run train_level_one to three for extracting the feature map. Otherwise, a MNH network or other transformation estimation methods need to be done first.
